-- AMC8 备考系统 - 数据库表结构

-- 启用 UUID 扩展
create extension if not exists "uuid-ossp";

-- 用户表
create table users (
  id uuid default uuid_generate_v4() primary key,
  name text not null unique,
  display_name text not null,
  age integer not null,
  avatar text,
  total_score integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 知识点进度表
create table topic_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  topic_id text not null,
  topic_name text not null,
  completed boolean default false,
  score integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, topic_id)
);

-- 错题表
create table wrong_answers (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  question_id text not null,
  question_text text not null,
  user_answer text,
  correct_answer text,
  topic text,
  error_type text,
  times_wrong integer default 1,
  last_attempted timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 练习记录表
create table practice_records (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  topic_id text,
  questions_count integer,
  correct_count integer,
  time_spent integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 插入默认用户
insert into users (name, display_name, age) values 
  ('matt', 'Matt', 11),
  ('chris', 'Chris', 9);

-- 初始化知识点进度
insert into topic_progress (user_id, topic_id, topic_name)
select 
  u.id,
  t.topic_id,
  t.topic_name
from users u
cross join (
  values 
    ('algebra-basics', '代数基础'),
    ('algebra-equations', '一次方程'),
    ('geometry-area', '面积与周长'),
    ('geometry-angles', '角度'),
    ('number-theory', '数论'),
    ('combinatorics', '组合数学'),
    ('logic', '逻辑推理')
) as t(topic_id, topic_name);
